In [ ]:
!git clone https://github.com/samarapires-ml/Buy-Now-Pay-Later--BNPL--Risk-Prediction.git

Cloning into 'Buy-Now-Pay-Later--BNPL--Risk-Prediction'...
remote: Enumerating objects: 93, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (85/85), done.
remote: Total 93 (delta 39), reused 20 (delta 4), pack-reused 0 (from 0)
Receiving objects: 100% (93/93), 8.59 MiB | 9.28 MiB/s, done.
Resolving deltas: 100% (39/39), done.
Updating files: 100% (20/20), done.

In [ ]:
%cd Buy-Now-Pay-Later--BNPL--Risk-Prediction

/content/Buy-Now-Pay-Later--BNPL--Risk-Prediction

In [ ]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
#load data
url = "https://raw.githubusercontent.com/samarapires-ml/Buy-Now-Pay-Later--BNPL--Risk-Prediction/main/data/processed/clean_train_data.csv"
df = pd.read_csv(url)

df.head()

,Customer_Age,Annual_Income,Credit_Score,Purchase_Amount,Checkout_Time_Seconds,Gender_Male,Gender_Non-Binary,Purchase_Category_Electronics,Purchase_Category_Fashion,Purchase_Category_Groceries,...,BNPL_Provider_Klarna,BNPL_Provider_Sezzle,Device_Type_Mobile,Device_Type_Tablet,Connection_Type_VPN,Connection_Type_WiFi,Browser_Edge,Browser_Firefox,Browser_Safari,target
0,0.449191,0.678213,1.276992,-0.269804,0.547276,False,False,False,False,False,...,False,False,True,False,False,True,False,True,False,1
1,-1.251365,-0.892115,-0.585550,-0.712582,0.074677,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,1
2,1.706123,1.499208,1.597902,-0.523022,0.212518,False,False,False,False,False,...,False,True,False,False,False,True,False,False,False,0
3,0.079505,-0.940859,-0.931630,-0.684289,1.512167,False,False,False,False,False,...,False,False,True,False,False,True,False,False,False,0
4,-1.399239,-0.813633,-0.874999,-0.486241,0.114060,True,False,True,False,False,...,False,True,False,False,False,False,False,False,False,1

In [ ]:
df.shape

(40000, 23)

In [ ]:
df.columns

Index(['Customer_Age', 'Annual_Income', 'Credit_Score', 'Purchase_Amount',
       'Checkout_Time_Seconds', 'Gender_Male', 'Gender_Non-Binary',
       'Purchase_Category_Electronics', 'Purchase_Category_Fashion',
       'Purchase_Category_Groceries', 'Purchase_Category_Home & Furniture',
       'Purchase_Category_Travel', 'BNPL_Provider_Afterpay',
       'BNPL_Provider_Klarna', 'BNPL_Provider_Sezzle', 'Device_Type_Mobile',
       'Device_Type_Tablet', 'Connection_Type_VPN', 'Connection_Type_WiFi',
       'Browser_Edge', 'Browser_Firefox', 'Browser_Safari', 'target'],
      dtype='object')

In [ ]:
df['target'].value_counts()

target
0    30719
1     9281
Name: count, dtype: int64

In [ ]:
#defining X and y
X_train = df.drop('target', axis=1)
y_train = df['target']

In [ ]:
#feature selection --> LASSO
from sklearn.linear_model import LassoCV

lasso = LassoCV(cv=10, random_state=42)
lasso.fit(X_train, y_train)

#selected_features
selected_features = X_train.columns[lasso.coef_ != 0]
print(selected_features)

Index(['Customer_Age', 'Annual_Income', 'Credit_Score', 'Purchase_Amount',
       'Checkout_Time_Seconds', 'Gender_Male', 'Purchase_Category_Electronics',
       'Purchase_Category_Home & Furniture', 'BNPL_Provider_Afterpay',
       'Device_Type_Mobile', 'Connection_Type_VPN', 'Connection_Type_WiFi'],
      dtype='object')

In [ ]:
X_train = df[selected_features]
y_train = df['target']

In [ ]:
url_test = "https://raw.githubusercontent.com/samarapires-ml/Buy-Now-Pay-Later--BNPL--Risk-Prediction/main/data/processed/clean_test_data.csv"
test = pd.read_csv(url_test)

In [ ]:
X_test = test[selected_features]
y_test = test['target']

In [ ]:
X_test

,Customer_Age,Annual_Income,Credit_Score,Purchase_Amount,Checkout_Time_Seconds,Gender_Male,Purchase_Category_Electronics,Purchase_Category_Home & Furniture,BNPL_Provider_Afterpay,Device_Type_Mobile,Connection_Type_VPN,Connection_Type_WiFi
0,0.818876,0.721660,-0.686228,-0.648923,1.610625,False,False,False,False,True,False,True
1,1.188562,0.439513,-0.189130,-0.457949,0.921417,True,False,False,True,True,False,True
2,1.336437,0.763861,-0.661058,-0.469266,-1.677880,True,False,False,False,False,False,True
3,-0.955616,0.793287,0.503030,2.840960,-0.358540,False,False,False,False,True,False,True
4,-0.364118,-0.710814,0.232458,-0.313657,0.921417,True,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,0.005567,1.497961,0.427522,0.201267,0.350360,True,True,False,False,False,False,False
9996,1.262500,0.674786,-0.717689,-0.412681,0.015602,False,False,False,False,False,False,True
9997,-0.438056,-0.949064,-1.277710,2.103940,-1.106822,True,False,False,False,False,False,False
9998,0.818876,0.014355,1.100805,-0.399949,1.413708,False,False,False,True,True,False,False
9999,-1.399239,-0.223479,0.408645,-0.494729,0.842651,False,False,False,False,True,False,False

In [ ]:
X_train.to_csv("X_train_latest.csv", index=False)
X_test.to_csv("X_test_n.csv", index=False)
y_train.to_csv("y_train_n.csv", index=False)
y_test.to_csv("y_test_n.csv", index=False)

In [ ]:
df = pd.read_csv("y_test_n.csv")
df.shape

(10000, 1)